# Generated by Django 5.1.4 on 2024-12-10 07:11

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', my_app.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('dentist', 'Dentist'), ('physician', 'Physician'), ('patient', 'Patient')], max_length=20, null=True),
        ),
    ]
