# Generated by Django 5.1.4 on 2024-12-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=15, unique=True)),
                ('priority_group', models.CharField(choices=[('FAC', 'Faculty'), ('PER', 'Personnel'), ('SEN', 'Senior Citizens'), ('STD', 'Students'), ('NON', 'Non-Academic Personnel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CONSULT', 'Consultation'), ('FOLLOWUP', 'Follow-Up'), ('CHECKUP', 'Check-Up')], max_length=10)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.patient')),
            ],
        ),
    ]
