# Generated by Django 5.1.4 on 2024-12-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_ticket_delete_appointment_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='queue_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
