# Generated by Django 5.1.4 on 2024-12-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_ticket_queue_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
