# Generated by Django 5.1.4 on 2024-12-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_patient_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('campus', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('course_year', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Non-academic', 'Non-academic')], default='Student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
