# Generated by Django 5.1.4 on 2024-12-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_patientaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
