# Generated by Django 5.1.4 on 2024-12-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_patientaccount_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
