# Generated by Django 5.1.4 on 2024-12-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_patientaccount_blood_type'),
        ('my_app', '0013_patientaccount_user'),
    ]

    operations = [
    ]
