# Generated by Django 5.1.4 on 2024-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_merge_20241230_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
