# Generated by Django 5.1.4 on 2024-12-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_patientaccount_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
