# Generated by Django 5.1.4 on 2024-12-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_medicalrecord_patient_delete_patient'),
        ('my_app', '0016_alter_patientaccount_email'),
    ]

    operations = [
    ]
