# Generated by Django 5.1.4 on 2024-12-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_merge_20241230_0952'),
        ('my_app', '0017_merge_20241230_1327'),
    ]

    operations = [
    ]
