# Generated by Django 5.1.3 on 2024-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_merge_20241230_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
