# Generated by Django 5.1.4 on 2024-12-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_merge_20241230_1602'),
        ('my_app', '0019_remove_patientaccount_user_and_more'),
    ]

    operations = [
    ]
