# Generated by Django 5.1.4 on 2024-12-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_alter_patientaccount_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
